import type { Metadata } from "next"
import "../globals.css"
import { Roboto } from 'next/font/google'
import { cn } from "@/lib/utils"
import { Toaster } from '@/components/ui/toaster'
import Sidebar from "@/components/sidebar/Sidebar"

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn('min-h-screen', roboto.className)}>
        <Toaster />
        <Sidebar />
        <main className="ml-[270px] p-2">
          {children}
        </main>
      </body>
    </html>
  );
}
