import type { Metadata } from "next"
import "../globals.css"
import { Roboto } from 'next/font/google'
import { cn } from "@/lib/utils"

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn('min-h-screen', roboto.className)}>
        <main className="h-screen flex justify-center items-center bg-gradient-to-t from-[#fbc2eb] to-[#a6c1ee]">
          {children}
        </main>
      </body>
    </html>
  );
}
